// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARv6CTJAEMCKc6OQxlHN6cKQ8iixeVab4',
    appId: '1:599090435663:web:fc457de248309b880abc3a',
    messagingSenderId: '599090435663',
    projectId: 'car-rent-45630',
    authDomain: 'car-rent-45630.firebaseapp.com',
    storageBucket: 'car-rent-45630.appspot.com',
    measurementId: 'G-R20HMBFBRM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdpKYV7r-IBQjWxdxpijxzSmmNiajJ3KA',
    appId: '1:599090435663:android:203c4798165415920abc3a',
    messagingSenderId: '599090435663',
    projectId: 'car-rent-45630',
    storageBucket: 'car-rent-45630.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzQUGLrgEJ3PxDynSlVo10sq7-ceNUTNQ',
    appId: '1:599090435663:ios:3b1c472989e649990abc3a',
    messagingSenderId: '599090435663',
    projectId: 'car-rent-45630',
    storageBucket: 'car-rent-45630.appspot.com',
    iosBundleId: 'com.carrent.com',
  );
}
